# MATRICES

* In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions arranged in rows and columns. The numbers in a matrix are called its elements or entries.
* Matrices have many uses in engineering, physics, economics, statistics, and various branches of mathematics.

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
zero_matrix = np.zeros((3,3))
ones_matrix = np.ones((2,4))
identity_matrix = np.eye((3))

In [4]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
matrix.shape

(3, 3)

In [9]:
matrix.size

9

### Basic Operations:

#### 1. Matrix Addition:

In [10]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[3,2,1],[6,5,4],[9,8,7]])

In [11]:
a1, a2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]]))

In [12]:
matrix_sum = a1 + a2
matrix_sum

array([[ 4,  4,  4],
       [10, 10, 10],
       [16, 16, 16]])

#### 2. Matrix Subtraction

In [13]:
matrix_diff = a1 - a2
matrix_diff

array([[-2,  0,  2],
       [-2,  0,  2],
       [-2,  0,  2]])

#### 3. Scalar Multiplication:

In [14]:
scalar = 3
s_matrix = matrix * scalar
s_matrix

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

#### 4. Matrix Multiplication

In [15]:
# Matrix multiplication
matrix_product = np.dot(a1,a2)
matrix_product

array([[ 42,  36,  30],
       [ 96,  81,  66],
       [150, 126, 102]])

In [16]:
# Element - wise multiplication
ele_matrix = a1 * a2
ele_matrix

array([[ 3,  4,  3],
       [24, 25, 24],
       [63, 64, 63]])

#### 5. Transpose of a Matrix

In [17]:
# Matrix as a Nested List

a = [[7,8,2,3,1,4],[5,1,3,4,6,2],[5,7,8,2,1,3]]
b = np.transpose(a)
print('a\n',a)
print('b\n',b)

a
 [[7, 8, 2, 3, 1, 4], [5, 1, 3, 4, 6, 2], [5, 7, 8, 2, 1, 3]]
b
 [[7 5 5]
 [8 1 7]
 [2 3 8]
 [3 4 2]
 [1 6 1]
 [4 2 3]]


In [18]:
# Transpose of a Matrix (as NumPy array)
a = np.array([[7,8,2,3,1,4],[5,1,3,4,6,2],[5,7,8,2,1,3]])
b = a.T  # T gives transpose 
print('a\n',a)
print('b\n',b)

a
 [[7 8 2 3 1 4]
 [5 1 3 4 6 2]
 [5 7 8 2 1 3]]
b
 [[7 5 5]
 [8 1 7]
 [2 3 8]
 [3 4 2]
 [1 6 1]
 [4 2 3]]


#### 6. Dot Product:

In [19]:
 # scalars
 a = 8
 b = 10
 z = np.dot(a,b)
 print(z)

80


In [20]:
 z = a * b
 print(z)

80


In [21]:
 # Nested list
 # 2D arrays or matrices
 a = [[7,8,2,3],[5,1,3,4],[5,7,8,2]]
 b = [[2,3,5,1,3],[1,5,3,2,4],[4,6,3,6,2],[3,1,6,4,2]]
 z = np.dot(a,b)
 print(z)
# General matrix multiplication - multiply each row to each column

[[ 39  76  83  47  63]
 [ 35  42  61  41  33]
 [ 55 100  82  75  63]]


In [22]:
 # Numpy array
 # 1D arrays or vectors
 a = np.array([3,4,5])  # or a = [3,4,5]
 b = np.array([1,5,2])  # or b = [1,5,2]
 z = np.dot(a,b)
 print(z)
# sum of the product of the column elements - (3*1)+(4*5)+(5*2)

33


In [23]:
# Direct Matrix Multiplication
z = np.matmul(a,b)
print(z)

33


#### 7. Matrix Inversion:

In [24]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

#### 8. Determinant of Matrix:

In [26]:
determinant = np.linalg.det(matrix)
determinant

-9.51619735392994e-16

#### 9. Rank of a Matrix:

In [27]:
rank = np.linalg.matrix_rank(matrix)
rank

2

#### 10. Diagonal Matrix:

In [28]:
diagonal_matrix = np.diag([1,2,3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

#### 11. Symmetric Matrix:

In [29]:
symmetric_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
symmetric_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 12. Orthogonal Matrix:

In [30]:
orthogonal_matrix = np.array([[0,1],[1,0]])
orthogonal_matrix

array([[0, 1],
       [1, 0]])

#### 13. Matrix Decomposition:

##### Singular Value Decomposition (SVD):

In [31]:
U, S, Vt = np.linalg.svd(matrix)

In [32]:
U, S, Vt

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

##### b. Eigen Value Decomposition

In [33]:
eigen_values, eigen_vectors = np.linalg.eig(matrix)

In [34]:
eigen_values, eigen_vectors

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

##### c. LU Decomposition